### PR TITLE
Feature/reporter state implementation

### PR DESCRIPTION
**Pull request by Claypuppet**
First version of new state implementations, not 100% sure if the upload to api is working but im connected to the wifi. my readings are invalid (no gps) so they wont post.

@robouden if you can test this and let me know, would be great!

### CODE REVIEW

**Comment by Claypuppet** [comment]
We now have 3 envs in platformio

-bgeigiecast, specific for the PCB,  might add ota to this
-wrover, for the wrover dev kit debug board
-wroom, i use this for the wemos board.

**Comment by Claypuppet** [comment]
Actually still have to check the api uploads, dont merge yet :)

**Comment by robouden** [comment]
Ok.. Let me know when you are done testing. Easy check for data coming in is at Grafana..

**Comment by robouden** [comment]
Do not work. BLE not active and can not connect to WiFi..

**Review by robouden — COMMENTED** [review]
I will check the build here too.

**Pull request merged**
